<?php
$this->session = \Config\Services::session();
$ASSETS_URL = getenv('ASSETS_URL');
?>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ABP-Podcast</title>
<link rel="icon" href="https://abp-podcast.keylines.in/uploads/1672119723WhatsApp Image 2022-12-27 at 11.06.49 AM.jpeg" type="image/x-icon">
<link rel="stylesheet" href="<?=$ASSETS_URL?>bootstrap/bootstrap-5.0.2-dist/bootstrap-5.0.2-dist/css/bootstrap-grid.min.css">
<link rel="stylesheet" href="<?=$ASSETS_URL?>fontawesome-free/css/all.css">
<link rel="stylesheet" href="<?=$ASSETS_URL?>splide-4.1.3/dist/css/splide.min.css">
<link rel="stylesheet" href="<?=$ASSETS_URL?>owl3.css">
<link rel="stylesheet" href="<?=$ASSETS_URL?>css/style.css">
<link rel="stylesheet" href="<?=$ASSETS_URL?>css/responsive.css">

<style type="text/css">
    @keyframes ldio-0lvymc0w5sdn-1 {
      0% { top: 36px; height: 128px }
      50% { top: 60px; height: 80px }
      100% { top: 60px; height: 80px }
    }
    @keyframes ldio-0lvymc0w5sdn-2 {
      0% { top: 41.99999999999999px; height: 116.00000000000001px }
      50% { top: 60px; height: 80px }
      100% { top: 60px; height: 80px }
    }
    @keyframes ldio-0lvymc0w5sdn-3 {
      0% { top: 48px; height: 104px }
      50% { top: 60px; height: 80px }
      100% { top: 60px; height: 80px }
    }
    .ldio-0lvymc0w5sdn div { position: absolute; width: 30px }.ldio-0lvymc0w5sdn div:nth-child(1) {
      left: 35px;
      background: #e15b64;
      animation: ldio-0lvymc0w5sdn-1 1s cubic-bezier(0,0.5,0.5,1) infinite;
      animation-delay: -0.2s
    }
    .ldio-0lvymc0w5sdn div:nth-child(2) {
      left: 85px;
      background: #f8b26a;
      animation: ldio-0lvymc0w5sdn-2 1s cubic-bezier(0,0.5,0.5,1) infinite;
      animation-delay: -0.1s
    }
    .ldio-0lvymc0w5sdn div:nth-child(3) {
      left: 135px;
      background: #abbd81;
      animation: ldio-0lvymc0w5sdn-3 1s cubic-bezier(0,0.5,0.5,1) infinite;
      animation-delay: undefineds
    }

    .loadingio-spinner-pulse-4ofwcox9r54 {
      width: 200px;
      height: 200px;
      /* display: inline-block;*/
/*      overflow: hidden;*/
      background: none;
      margin: 0 auto;      
    }
    .ldio-0lvymc0w5sdn {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(1);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-0lvymc0w5sdn div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
</style>